@ECHO OFF

SET STARTING_DIRECTORY=%CD%
SET OUTPUT=BINARIES
SET DIRECTORY=TI83PLUS
SET FILENAME=SPLASH
SET INCLUDE_FILE=TI83PLUS.INC
SET SOURCE_FILE=%FILENAME%.Z80.ASM
SET DATA_FILE=%FILENAME%.DATA.Z80.ASM
SET BINARY_FILE=%FILENAME%.BIN
SET LISTING_FILE=%FILENAME%.LST
SET EXPORT_FILE=%FILENAME%.8XP

::ASSEMBLE
CD %DIRECTORY%
COPY %INCLUDE_FILE% ..
COPY %SOURCE_FILE% ..
COPY %DATA_FILE% ..
CD ..
MOVE %INCLUDE_FILE% TOOLCHAIN
MOVE %SOURCE_FILE% TOOLCHAIN
MOVE %DATA_FILE% TOOLCHAIN
CD TOOLCHAIN
MOVE %INCLUDE_FILE% TASM
MOVE %SOURCE_FILE% TASM
MOVE %DATA_FILE% TASM
CD TASM
IF NOT EXIST TASM.EXE GOTO MISSING_ASSEMBLER
TASM.EXE -80 -i -b %SOURCE_FILE% %BINARY_FILE%

::PREPARE
MOVE %INCLUDE_FILE% ..\CACHE
MOVE %SOURCE_FILE% ..\CACHE
MOVE %DATA_FILE% ..\CACHE
IF NOT EXIST %BINARY_FILE% GOTO FAIL_ASSEMBLE
COPY %BINARY_FILE% ..\CACHE
MOVE %BINARY_FILE% ..\DEVPAC8X
IF NOT EXIST %LISTING_FILE% GOTO FAIL_ASSEMBLE
COPY %LISTING_FILE% ..\CACHE
MOVE %LISTING_FILE% ..\DEVPAC8X

::EXPORT
CD ..\DEVPAC8X
IF NOT EXIST DEVPAC8X.COM GOTO MISSING_EXPORTER
::DEVPAC8X %FILENAME%
SET DOSBOX_PATH="C:\Program Files (x86)\DOSBox-0.74-3\DOSBox.exe"
%DOSBOX_PATH% -c "MOUNT C %CD%" -c "C:" -c "DEVPAC8X %FILENAME%" -c "exit"
IF NOT EXIST %EXPORT_FILE% GOTO FAIL_EXPORT
DEL %BINARY_FILE%
DEL %LISTING_FILE%
COPY %EXPORT_FILE% ..\CACHE
MOVE %EXPORT_FILE% ..
CD ..
MOVE %EXPORT_FILE% ..\%OUTPUT%
CD ..

::TODO RUN OR TRANSFER

ECHO Success.
GOTO FIN


:MISSING_ASSEMBLER
ECHO Missing Assembler
GOTO FIN

:FAIL_ASSEMBLE
ECHO Fail Assemble
GOTO FIN

:MISSING_EXPORTER
ECHO Missing Exporter
GOTO FIN

:FAIL_EXPORT
ECHO Fail Export
GOTO FIN

:FIN
CD %STARTING_DIRECTORY%