
;========================================
;       PROGRAM SPLASH					;
;       VERSION 1.0.0					;
;       RUNTIME ASSEMBLY FILE			;
;		FILENAME BUFFERS.Z80.ASM		;
;       AUTHOR ERIC NANTEL				;
;		COUNTRY CANADA					;
;       COPYRIGHT 2023-2024				;
;		SOURCE CODE AVAILABLE ON		;
;		GITHUB.COM/ERICNANTEL/SPLASH	;
;========================================

.NOLIST
;========================================
;       NO LISTING                      ;
;========================================
CACHE_LINE_LENGTH			EQU 12;16
CACHE_LINE_EXTRA_LENGTH		EQU 1
CACHE_WIDTH					EQU CACHE_LINE_LENGTH*8
CACHE_HEIGHT				EQU 128
CACHE_BUFFER_LENGTH			EQU CACHE_LINE_LENGTH*CACHE_HEIGHT

FREE_MEMORY_NEEDED			EQU CACHE_LINE_LENGTH+CACHE_LINE_EXTRA_LENGTH+CACHE_BUFFER_LENGTH

CACHE_LINE_OFFSET			EQU 0
CACHE_LINE_EXTRA_OFFSET		EQU CACHE_LINE_OFFSET+CACHE_LINE_LENGTH
CACHE_BUFFER_OFFSET			EQU CACHE_LINE_EXTRA_OFFSET+CACHE_LINE_EXTRA_LENGTH

.LIST

.end
