
;========================================
;       PROGRAM SPLASH					;
;       VERSION 1.0.0					;
;       RUNTIME ASSEMBLY FILE			;
;		FILENAME BUFFERS.Z80.ASM		;
;       AUTHOR ERIC NANTEL				;
;		COUNTRY CANADA					;
;       COPYRIGHT 2023-2024				;
;		SOURCE CODE AVAILABLE ON		;
;		GITHUB.COM/ERICNANTEL/SPLASH	;
;========================================

.NOLIST
;========================================
;       NO LISTING                      ;
;========================================
CACHE_LINE_LENGTH				EQU 12;16
CACHE_LINE_EXTRA_LENGTH			EQU 1
CACHE_WIDTH						EQU CACHE_LINE_LENGTH*8
CACHE_HEIGHT					EQU 128
CACHE_BUFFER_LENGTH				EQU CACHE_LINE_LENGTH*CACHE_HEIGHT
TILE_HEIGHT						EQU 8;16 it is possible to use 8x16
TILE_IMAGE_LENGTH				EQU 1*TILE_HEIGHT
TILES_PER_CACHE_COLUMNS			EQU CACHE_HEIGHT/TILE_HEIGHT
TILE_INDEX_BUFFER_LENGTH		EQU TILES_PER_CACHE_COLUMNS*CACHE_LINE_LENGTH ;Cannot be over 255 !
TILE_IMAGE_BUFFER_LENGTH		EQU 2
LVL_H_BUFFER_LENGTH				EQU 2
LVL_TD_BUFFER_LENGTH			EQU 2

FREE_MEMORY_NEEDED				EQU CACHE_LINE_LENGTH+CACHE_LINE_EXTRA_LENGTH+CACHE_BUFFER_LENGTH+TILE_INDEX_BUFFER_LENGTH+TILE_IMAGE_BUFFER_LENGTH+LVL_H_BUFFER_LENGTH+LVL_TD_BUFFER_LENGTH

CACHE_LINE_OFFSET				EQU 0
CACHE_LINE_EXTRA_OFFSET			EQU CACHE_LINE_OFFSET+CACHE_LINE_LENGTH
CACHE_BUFFER_OFFSET				EQU CACHE_LINE_EXTRA_OFFSET+CACHE_LINE_EXTRA_LENGTH
TILE_INDEX_BUFFER_OFFSET		EQU CACHE_BUFFER_OFFSET+CACHE_BUFFER_LENGTH
TILE_IMAGE_BUFFER_OFFSET		EQU TILE_INDEX_BUFFER_OFFSET+TILE_INDEX_BUFFER_LENGTH
LVL_H_BUFFER_OFFSET				EQU TILE_IMAGE_BUFFER_OFFSET+TILE_IMAGE_BUFFER_LENGTH
LVL_TD_BUFFER_OFFSET			EQU LVL_H_BUFFER_OFFSET+LVL_H_BUFFER_LENGTH

.LIST

.end
