
;========================================
;       PROGRAM SPLASH					;
;       VERSION 1.0.0					;
;       RUNTIME ASSEMBLY FILE			;
;		FILENAME BUFFERS.Z80.ASM		;
;       AUTHOR ERIC NANTEL				;
;		COUNTRY CANADA					;
;       COPYRIGHT 2023-2024				;
;		SOURCE CODE AVAILABLE ON		;
;		GITHUB.COM/ERICNANTEL/SPLASH	;
;========================================

.NOLIST
;========================================
;       NO LISTING                      ;
;========================================
DATA_LINE_LENGTH				EQU 24 ;16 12;Needs to be at least size of screen_line !
DATA_WIDTH						EQU DATA_LINE_LENGTH*8
DATA_HEIGHT						EQU 160 ;128 64;Needs to be at least size of screen_height !
CACHE_LINE_LENGTH				EQU DATA_LINE_LENGTH+1 ;We need that extra byte !
CACHE_WIDTH						EQU CACHE_LINE_LENGTH*8
CACHE_HEIGHT					EQU DATA_HEIGHT ;Same as data_height !
CACHE_BUFFER_LENGTH				EQU CACHE_LINE_LENGTH*CACHE_HEIGHT
TILE_HEIGHT						EQU 8
TILE_IMAGE_LENGTH				EQU 1*TILE_HEIGHT
TILES_PER_DATA_COLUMNS			EQU DATA_HEIGHT/TILE_HEIGHT
TILE_INDEX_BUFFER_LENGTH		EQU TILES_PER_DATA_COLUMNS*DATA_LINE_LENGTH ;Cannot be over 255 !
TILE_IMAGE_BUFFER_LENGTH		EQU 2
LVL_H_BUFFER_LENGTH				EQU 2
LVL_TD_BUFFER_LENGTH			EQU 2

FREE_MEMORY_NEEDED				EQU CACHE_BUFFER_LENGTH+TILE_INDEX_BUFFER_LENGTH+TILE_IMAGE_BUFFER_LENGTH+LVL_H_BUFFER_LENGTH+LVL_TD_BUFFER_LENGTH

CACHE_BUFFER_OFFSET				EQU 0
TILE_INDEX_BUFFER_OFFSET		EQU CACHE_BUFFER_OFFSET+CACHE_BUFFER_LENGTH
TILE_IMAGE_BUFFER_OFFSET		EQU TILE_INDEX_BUFFER_OFFSET+TILE_INDEX_BUFFER_LENGTH
LVL_H_BUFFER_OFFSET				EQU TILE_IMAGE_BUFFER_OFFSET+TILE_IMAGE_BUFFER_LENGTH
LVL_TD_BUFFER_OFFSET			EQU LVL_H_BUFFER_OFFSET+LVL_H_BUFFER_LENGTH

.LIST

.end
