
;========================================
;       PROGRAM SPLASH					;
;       VERSION 1.0.0					;
;       RUNTIME ASSEMBLY FILE			;
;		FILENAME GAMEPLAY.Z80.ASM		;
;       AUTHOR ERIC NANTEL				;
;		COUNTRY CANADA					;
;       COPYRIGHT 2023-2024				;
;		SOURCE CODE AVAILABLE ON		;
;		GITHUB.COM/ERICNANTEL/SPLASH	;
;========================================

.NOLIST
;========================================
;       NO LISTING                      ;
;========================================
GCameraWorldCoordY					EQU _AppBuffer + 0
GCameraWorldCoordX					EQU _AppBuffer + 1
GCameraBitDistance					EQU _AppBuffer + 2
GCameraWorldOffsetY					EQU _AppBuffer + 3
GCameraWorldOffsetX					EQU _AppBuffer + 4
GCameraViewportSizeY				EQU _AppBuffer + 5
GCameraViewportSizeX				EQU _AppBuffer + 6
GCameraFlags						EQU	_AppBuffer + 7
GPlayerWorldCoordY					EQU	_AppBuffer + 8
GPlayerWorldCoordX					EQU _AppBuffer + 9
GPlayerFlags						EQU _AppBuffer + 10
GGameplayInputFlags					EQU _AppBuffer + 11
GBufferStartAddressLow				EQU _AppBuffer + 12
GBufferStartAddressHigh				EQU _AppBuffer + 13
GBufferEndAddressLow				EQU _AppBuffer + 14
GBufferEndAddressHigh				EQU _AppBuffer + 15
GCacheLineAddressLow				EQU _AppBuffer + 16
GCacheLineAddressHigh				EQU _AppBuffer + 17
GCacheBufferAddressLow				EQU _AppBuffer + 18
GCacheBufferAddressHigh				EQU _AppBuffer + 19
GTileIndexBufferAddressLow			EQU _AppBuffer + 20
GTileIndexBufferAddressHigh			EQU _AppBuffer + 21
GTileImageBufferAddressLow			EQU _AppBuffer + 22
GTileImageBufferAddressHigh			EQU _AppBuffer + 23
GLevelHBufferAddressLow				EQU _AppBuffer + 24
GLevelHBufferAddressHigh			EQU _AppBuffer + 25
GLevelTDBufferAddressLow			EQU _AppBuffer + 24
GLevelTDBufferAddressHigh			EQU _AppBuffer + 25

CAMERA_VISIBLE_FLAG					EQU 0
PLAYER_VISIBLE_FLAG					EQU 0
PLAYER_ATTACH_FLAG					EQU 1
GAMEPLAY_INPUT_KEY_DOWN_FLAG		EQU 0
GAMEPLAY_INPUT_KEY_LEFT_FLAG		EQU 1
GAMEPLAY_INPUT_KEY_RIGHT_FLAG		EQU 2
GAMEPLAY_INPUT_KEY_UP_FLAG			EQU 3
GAMEPLAY_INPUT_KEY_ALPHA_FLAG		EQU 4
GAMEPLAY_INPUT_KEY_2ND_FLAG			EQU 5
GAMEPLAY_INPUT_KEY_MODE_FLAG		EQU 6
GAMEPLAY_INPUT_KEY_DEL_FLAG			EQU 7

; TODO: Move this somewhere like data folder
; Because these are not runtime but data related

; NOTE: We need to put this in another file perhaps..
; TILE_HEIGHT							EQU 8;16 it is possible to use 8x16
; TILE_IMAGE_LENGTH					EQU 1*TILE_HEIGHT

TILE_IMAGE_BLANK_INDEX				EQU 0
TILE_IMAGE_BRICKCENTER_INDEX		EQU 1
TILE_IMAGE_BRICKLEFT_INDEX			EQU 2
TILE_IMAGE_BRICKRIGHT_INDEX			EQU 3
TILE_IMAGE_BRICKTOPC_INDEX			EQU 4
TILE_IMAGE_BRICKTOPL_INDEX			EQU 5
TILE_IMAGE_BRICKTOPR_INDEX			EQU 6
TILE_IMAGE_GRASS_INDEX				EQU 7
TILE_IMAGE_BUSH_INDEX				EQU 8
TILE_IMAGE_HOLE_INDEX				EQU 9
TILE_IMAGE_HEART_INDEX				EQU 10
TILE_IMAGE_GEMSTONE_INDEX			EQU 11
TILE_IMAGE_PAVING1_INDEX			EQU 12
TILE_IMAGE_PLANK1_INDEX				EQU 13
TILE_IMAGE_CHEST1_INDEX				EQU 14
TILE_IMAGE_WINDOW_INDEX				EQU 15
TILE_IMAGE_EGGSHELL_INDEX			EQU 16
TILE_IMAGE_PATTERN1_INDEX			EQU 17
TILE_IMAGE_PATTERN2_INDEX			EQU 18

TILE_IMAGE_BLANK_OFFSET				EQU TILE_IMAGE_BLANK_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_BRICKCENTER_OFFSET		EQU TILE_IMAGE_BRICKCENTER_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_BRICKLEFT_OFFSET			EQU TILE_IMAGE_BRICKLEFT_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_BRICKRIGHT_OFFSET		EQU TILE_IMAGE_BRICKRIGHT_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_BRICKTOPC_OFFSET			EQU TILE_IMAGE_BRICKTOPC_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_BRICKTOPL_OFFSET			EQU TILE_IMAGE_BRICKTOPL_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_BRICKTOPR_OFFSET			EQU TILE_IMAGE_BRICKTOPR_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_GRASS_OFFSET				EQU TILE_IMAGE_GRASS_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_BUSH_OFFSET				EQU TILE_IMAGE_BUSH_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_HOLE_OFFSET				EQU TILE_IMAGE_HOLE_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_HEART_OFFSET				EQU TILE_IMAGE_HEART_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_GEMSTONE_OFFSET			EQU TILE_IMAGE_GEMSTONE_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_PAVING1_OFFSET			EQU TILE_IMAGE_PAVING1_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_PLANK1_OFFSET			EQU TILE_IMAGE_PLANK1_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_CHEST1_OFFSET			EQU TILE_IMAGE_CHEST1_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_WINDOW_OFFSET			EQU TILE_IMAGE_WINDOW_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_EGGSHELL_OFFSET			EQU TILE_IMAGE_EGGSHELL_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_PATTERN1_OFFSET			EQU TILE_IMAGE_PATTERN1_INDEX*TILE_IMAGE_LENGTH
TILE_IMAGE_PATTERN2_OFFSET			EQU TILE_IMAGE_PATTERN2_INDEX*TILE_IMAGE_LENGTH

LVL_HEADER_LENGTH				EQU 2
LVL_TILE_DATA_LENGTH			EQU 1 ;Only need 6bits (up to 64 tiles)

LVL_THALASLAND_TD_LENGTH		EQU 16*16*LVL_TILE_DATA_LENGTH
LVL_THALASHOME_TD_LENGTH		EQU 1*1*LVL_TILE_DATA_LENGTH
LVL_THALASCASTLE_TD_LENGTH		EQU 1*1*LVL_TILE_DATA_LENGTH
LVL_THALASCAVE_TD_LENGTH		EQU 1*1*LVL_TILE_DATA_LENGTH

LVL_THALASLAND_LENGTH			EQU LVL_HEADER_LENGTH+LVL_THALASLAND_TD_LENGTH
LVL_THALASHOME_LENGTH			EQU LVL_HEADER_LENGTH+LVL_THALASHOME_TD_LENGTH
LVL_THALASCASTLE_LENGTH			EQU LVL_HEADER_LENGTH+LVL_THALASCASTLE_TD_LENGTH
LVL_THALASCAVE_LENGTH			EQU LVL_HEADER_LENGTH+LVL_THALASCAVE_TD_LENGTH

LVL_THALASLAND_INDEX			EQU 0
LVL_THALASHOME_INDEX			EQU 1
LVL_THALASCASTLE_INDEX			EQU 2
LVL_THALASCAVE_INDEX			EQU 3

LVL_THALASLAND_H_OFFSET			EQU 0
LVL_THALASLAND_TD_OFFSET		EQU LVL_THALASLAND_H_OFFSET+LVL_HEADER_LENGTH
LVL_THALASHOME_H_OFFSET			EQU LVL_THALASLAND_TD_OFFSET+LVL_THALASLAND_TD_LENGTH
LVL_THALASHOME_TD_OFFSET		EQU LVL_THALASLAND_H_OFFSET+LVL_HEADER_LENGTH
LVL_THALASCASTLE_H_OFFSET		EQU LVL_THALASLAND_TD_OFFSET+LVL_THALASHOME_TD_LENGTH
LVL_THALASCASTLE_TD_OFFSET		EQU LVL_THALASLAND_H_OFFSET+LVL_HEADER_LENGTH
LVL_THALASCAVE_H_OFFSET			EQU LVL_THALASLAND_TD_OFFSET+LVL_THALASCASTLE_TD_LENGTH
LVL_THALASCAVE_TD_OFFSET		EQU LVL_THALASLAND_H_OFFSET+LVL_HEADER_LENGTH

.LIST

.end
